### ISSUE TITLE
No communication

### ISSUE THREAD

**Issue by indivliving** [siku2/hass-komfovent-c5#10]
My C5 is on and running. Accessible via IP and the web interface. Unfortunately, no data is loaded from the system via the addon. The setup runs through, but afterwards there is no data retrieval as it seems. Do settings have to be made on the device itself?
Thank You

**Comment by siku2** [comment]
I want to help out, but I'm gonna need more information. Are you using the latest version (0.3.1)? Do you get any errors in the logs? Be sure to enable "Debug Logging" for the integration and attach the logs here as well.

As for your question, no settings need to be changed on the device itself (at least as far as I'm aware).

Other things that could be useful:

- screenshot of the overview page on your komfovent's web frontend.
- screenshot of the "Control Unit Status" section in the "Alarms / Status" tab of the web frontend (it contains a bunch of version information)

**Comment by indivliving** [comment]
Hello, yes latest Version is installed. Yes there ist following error in the log:


__________________________________

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/komfovent_c5/api/client.py:83
Integration: Komfovent C5 (documentation, issues)
First occurred: 11:04:55 (1 occurrences)
Last logged: 11:04:55

Error setting up entry 192.168.122.14 for komfovent_c5
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 116, in async_setup_entry
    await setup_coordinator(hass, entry)
  File "/config/custom_components/komfovent_c5/__init__.py", line 106, in setup_coordinator
    coordinator = await KomfoventCoordinator.build(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 88, in build
    await coordinator._initalize(client, entry)
  File "/config/custom_components/komfovent_c5/__init__.py", line 74, in _initalize
    self.settings_state = await Settings(client).read_all()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/settings.py", line 161, in read_all
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 83, in read_many_u16
    await self._modbus.read_holding_registers(address, count=count)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/mixin.py", line 102, in read_holding_registers
    return self.execute(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymodbus/client/base.py", line 178, in execute
    raise ConnectionException(f"Not connected[{str(self)}]")
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Not connected[AsyncModbusTcpClient 192.168.122.14:502]

__________________________________


![Bildschirmfoto 2023-08-21 um 11 09 10](https://github.com/siku2/hass-komfovent-c5/assets/59666932/24fa9fce-9638-4a9c-8d34-71c1dc005097)
![Bildschirmfoto 2023-08-21 um 11 09 37](https://github.com/siku2/hass-komfovent-c5/assets/59666932/3cbce9c2-7707-4f10-a557-258929432a03)
![Bildschirmfoto 2023-08-21 um 11 10 12](https://github.com/siku2/hass-komfovent-c5/assets/59666932/fe217d55-45da-4813-a2f9-96504f6d139a)

**Comment by siku2** [comment]
It's interesting how different our versions are:
![image](https://github.com/siku2/hass-komfovent-c5/assets/16530283/e21ea129-fd16-4d62-baa2-11ef2d78ad22)

There's a chance that it has something to do with this. I remember I had an issue with my device and a service technician performed an update a few months ago, before I even created the integration.

I'm working on a few modifications of the integration that will help us debug this, but for now a few follow up questions:

- Is the IP 192.168.122.14 still correct? Dumb question, I know, but the integration doesn't automatically follow DHCP re-assignments and based on the address it's not obvious whether it's static.
- Can you connect to the device using the "Komfovent C5: Local network" app?

**Comment by siku2** [comment]
@indivliving I just released a new version with some additional logging to help track this down. The aforementioned questions are still relevant, but please also try it out with the new version.

Be sure to enable "debug logging" for the Komfovent integration on the integration page before you restart:
![image](https://github.com/siku2/hass-komfovent-c5/assets/16530283/acf3996b-6c49-43c5-9ea0-76a68aa5f051)

**Comment by indivliving** [comment]
The ip is fixed in the device. No other device or app should connect to the Komfovent. I have now changed the ip address to a different one as a test to exclude old or incorrect connections.

Debug
————

2023-08-21 21:30:48.790 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] connecting to ('192.168.122.14', 502)
2023-08-21 21:30:48.792 DEBUG (MainThread) [pymodbus.logging] Connecting to 192.168.122.14:502.
2023-08-21 21:30:48.792 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-08-21 21:30:48.811 DEBUG (MainThread) [pymodbus.logging] Connected to comm
2023-08-21 21:30:48.813 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x1 0xc1 0x0 0x26
2023-08-21 21:30:48.813 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-08-21 21:30:48.831 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x14 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:48.832 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x14 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:48.832 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x14 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:48.832 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:48.832 DEBUG (MainThread) [pymodbus.logging] Getting transaction 1
2023-08-21 21:30:48.833 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x2 0x0 0x0 0x0 0x6 0x0 0x3 0x3 0xe7 0x0 0x1
2023-08-21 21:30:48.833 DEBUG (MainThread) [pymodbus.logging] Adding transaction 2
2023-08-21 21:30:48.836 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:48.837 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:48.837 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:48.837 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:48.837 DEBUG (MainThread) [pymodbus.logging] Getting transaction 2
2023-08-21 21:30:48.853 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x3 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4b 0x0 0x1
2023-08-21 21:30:48.853 DEBUG (MainThread) [pymodbus.logging] Adding transaction 3
2023-08-21 21:30:48.854 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:48.854 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:48.854 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:48.854 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:48.855 DEBUG (MainThread) [pymodbus.logging] Getting transaction 3
2023-08-21 21:30:48.855 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x4 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4c 0x0 0xe1
2023-08-21 21:30:48.855 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4
2023-08-21 21:30:48.861 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:48.861 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:48.861 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:48.861 DEBUG (MainThread) [pymodbus.logging] Factory Response[131]
2023-08-21 21:30:48.861 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4
2023-08-21 21:30:48.864 ERROR (MainThread) [custom_components.komfovent_c5] Unexpected error fetching komfovent_c5 data: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 83, in _async_update_data
    return await KomfoventState.read_all(self.client, self.settings_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 42, in read_all
    alarm_history=await alarms.read_history(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/alarms.py", line 105, in read_history
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 106, in read_many_u16
    assert not read_respones.isError()
AssertionError
2023-08-21 21:30:48.875 DEBUG (MainThread) [custom_components.komfovent_c5] Finished fetching komfovent_c5 data in 0.086 seconds (success: False)
2023-08-21 21:30:48.876 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.122.14' for komfovent_c5 integration not ready yet; Retrying in background
2023-08-21 21:30:48.892 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] closing the connection
2023-08-21 21:30:48.909 DEBUG (MainThread) [pymodbus.logging] Connection lost comm due to None
2023-08-21 21:30:51.648 WARNING (MainThread) [xknx.log] Error: KNX bus did not respond in time (2.0 secs) to GroupValueRead request for: 1/1/88
2023-08-21 21:30:51.655 WARNING (MainThread) [xknx.log] Could not sync group address '1/1/88' (EVENT G11 - Brightness)
2023-08-21 21:30:54.244 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] connecting to ('192.168.122.14', 502)
2023-08-21 21:30:54.245 DEBUG (MainThread) [pymodbus.logging] Connecting to 192.168.122.14:502.
2023-08-21 21:30:54.246 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-08-21 21:30:54.258 DEBUG (MainThread) [pymodbus.logging] Connected to comm
2023-08-21 21:30:54.261 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x1 0xc1 0x0 0x26
2023-08-21 21:30:54.261 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-08-21 21:30:54.277 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x19 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:54.278 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x19 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:54.278 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x19 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:30:54.279 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:54.280 DEBUG (MainThread) [pymodbus.logging] Getting transaction 1
2023-08-21 21:30:54.285 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x2 0x0 0x0 0x0 0x6 0x0 0x3 0x3 0xe7 0x0 0x1
2023-08-21 21:30:54.285 DEBUG (MainThread) [pymodbus.logging] Adding transaction 2
2023-08-21 21:30:54.304 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:54.305 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:54.306 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:30:54.306 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:54.307 DEBUG (MainThread) [pymodbus.logging] Getting transaction 2
2023-08-21 21:30:54.310 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x3 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4b 0x0 0x1
2023-08-21 21:30:54.311 DEBUG (MainThread) [pymodbus.logging] Adding transaction 3
2023-08-21 21:30:54.318 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:54.319 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:54.319 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:30:54.320 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:30:54.320 DEBUG (MainThread) [pymodbus.logging] Getting transaction 3
2023-08-21 21:30:54.321 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x4 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4c 0x0 0xe1
2023-08-21 21:30:54.322 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4
2023-08-21 21:30:54.327 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:54.328 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:54.329 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:30:54.329 DEBUG (MainThread) [pymodbus.logging] Factory Response[131]
2023-08-21 21:30:54.330 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4
2023-08-21 21:30:54.336 ERROR (MainThread) [custom_components.komfovent_c5] Unexpected error fetching komfovent_c5 data: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 83, in _async_update_data
    return await KomfoventState.read_all(self.client, self.settings_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 42, in read_all
    alarm_history=await alarms.read_history(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/alarms.py", line 105, in read_history
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 106, in read_many_u16
    assert not read_respones.isError()
AssertionError
2023-08-21 21:30:54.365 DEBUG (MainThread) [custom_components.komfovent_c5] Finished fetching komfovent_c5 data in 0.121 seconds (success: False)
2023-08-21 21:30:54.367 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] closing the connection
2023-08-21 21:30:54.369 DEBUG (MainThread) [pymodbus.logging] Connection lost comm due to None
2023-08-21 21:31:04.486 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] connecting to ('192.168.122.14', 502)
2023-08-21 21:31:04.487 DEBUG (MainThread) [pymodbus.logging] Connecting to 192.168.122.14:502.
2023-08-21 21:31:04.487 DEBUG (MainThread) [pymodbus.logging] Connecting comm
2023-08-21 21:31:04.494 DEBUG (MainThread) [pymodbus.logging] Connected to comm
2023-08-21 21:31:04.496 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x1 0x0 0x0 0x0 0x6 0x0 0x3 0x1 0xc1 0x0 0x26
2023-08-21 21:31:04.498 DEBUG (MainThread) [pymodbus.logging] Adding transaction 1
2023-08-21 21:31:04.513 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x24 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:31:04.514 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x24 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:31:04.515 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x1 0x0 0x0 0x0 0x4f 0x0 0x3 0x4c 0x14 0x1a 0x0 0x24 0x0 0x1 0x8 0x15 0x7 0xe7 0x0 0x4 0x0 0x7 0xc0 0xa8 0x7a 0xe 0x0 0x0 0x39 0x31 0x34 0x31 0x38 0x33 0x0 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0x4b 0x6f 0x6d 0x66 0x6f 0x76 0x65 0x6e 0x74 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xff 0xff 0xff 0x0 0x0 0xa 0x0 0x0 0x0 0x1 0xba 0xc0 0x0 0x0 0x0 0x32
2023-08-21 21:31:04.515 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:31:04.516 DEBUG (MainThread) [pymodbus.logging] Getting transaction 1
2023-08-21 21:31:04.518 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x2 0x0 0x0 0x0 0x6 0x0 0x3 0x3 0xe7 0x0 0x1
2023-08-21 21:31:04.519 DEBUG (MainThread) [pymodbus.logging] Adding transaction 2
2023-08-21 21:31:04.520 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:31:04.521 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:31:04.521 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x2 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x0
2023-08-21 21:31:04.522 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:31:04.522 DEBUG (MainThread) [pymodbus.logging] Getting transaction 2
2023-08-21 21:31:04.523 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x3 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4b 0x0 0x1
2023-08-21 21:31:04.524 DEBUG (MainThread) [pymodbus.logging] Adding transaction 3
2023-08-21 21:31:04.525 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:31:04.525 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:31:04.526 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x3 0x0 0x0 0x0 0x5 0x0 0x3 0x2 0x0 0x2d
2023-08-21 21:31:04.527 DEBUG (MainThread) [pymodbus.logging] Factory Response[ReadHoldingRegistersResponse': 3]
2023-08-21 21:31:04.527 DEBUG (MainThread) [pymodbus.logging] Getting transaction 3
2023-08-21 21:31:04.528 DEBUG (MainThread) [pymodbus.logging] send: 0x0 0x4 0x0 0x0 0x0 0x6 0x0 0x3 0x4 0x4c 0x0 0xe1
2023-08-21 21:31:04.529 DEBUG (MainThread) [pymodbus.logging] Adding transaction 4
2023-08-21 21:31:04.530 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:31:04.531 DEBUG (MainThread) [pymodbus.logging] recv: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:31:04.531 DEBUG (MainThread) [pymodbus.logging] Processing: 0x0 0x4 0x0 0x0 0x0 0x3 0x0 0x83 0x3
2023-08-21 21:31:04.533 DEBUG (MainThread) [pymodbus.logging] Factory Response[131]
2023-08-21 21:31:04.534 DEBUG (MainThread) [pymodbus.logging] Getting transaction 4
2023-08-21 21:31:04.536 ERROR (MainThread) [custom_components.komfovent_c5] Unexpected error fetching komfovent_c5 data: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 83, in _async_update_data
    return await KomfoventState.read_all(self.client, self.settings_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 42, in read_all
    alarm_history=await alarms.read_history(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/alarms.py", line 105, in read_history
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/client.py", line 106, in read_many_u16
    assert not read_respones.isError()
AssertionError
2023-08-21 21:31:04.556 DEBUG (MainThread) [custom_components.komfovent_c5] Finished fetching komfovent_c5 data in 0.070 seconds (success: False)
2023-08-21 21:31:04.558 DEBUG (MainThread) [custom_components.komfovent_c5.api.client] closing the connection
2023-08-21 21:31:04.562 DEBUG (MainThread) [pymodbus.logging] Connection lost comm due to None

**Comment by siku2** [comment]
@indivliving perfect, thanks. Looks like the integration is trying to read registers your Komfovent doesn't like. I should be able to fix this tomorrow

**Comment by siku2** [comment]
@indivliving, just released version 0.3.3, which should hopefully fix this issue.

**Comment by indivliving** [comment]
🎉🎉🎉 YES!!! Now it work‘s perfect. Big thank You!

**Comment by siku2** [comment]
Alright, I'm gonna close this issue then. Let me know if anything else comes up.
