### ISSUE TITLE
Failed to connect: [Errno 110] Connect call failed

### ISSUE THREAD

**Issue by colseven** [siku2/hass-komfovent-c5#4]
same error even after updating to the latest version :( do you have an idea what could be the reason?

```
Logger: pymodbus.client.asynchronous.async_io
Source: /usr/local/lib/python3.10/site-packages/pymodbus/client/asynchronous/async_io/__init__.py:307 
First occurred: 04:46:04 (102 occurrences) 
Last logged: 04:49:24


Failed to connect: [Errno 110] Connect call failed ('192.168.178.50', 502)
```

and

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.komfovent_c5
Source: custom_components/komfovent_c5/api/client.py:101 
Integration: Komfovent C5 (documentation, issues) 
First occurred: 05:01:50 (1 occurrences) 
Last logged: 05:01:50

Unexpected error fetching state data: Modbus Error: [Connection] Connection lost during request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/komfovent_c5/__init__.py", line 66, in __fetch_data
    return await KomfoventState.read_all(self.client, self.settings_state)
  File "/config/custom_components/komfovent_c5/__init__.py", line 54, in read_all
    functions=await Functions(client).read_all(),
  File "/config/custom_components/komfovent_c5/api/functions.py", line 39, in read_all
    regs = await self._client.read_many_u16(
  File "/config/custom_components/komfovent_c5/api/client.py", line 101, in read_many_u16
    await protocol.read_holding_registers(address, count=count)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/asynchronous/async_io/__init__.py", line 35, in execute
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Connection lost during request

```

**Comment by colseven** [comment]
absolutely safe!!

**Comment by colseven** [comment]
Newest Version this error, what ca i do?

`Logger: homeassistant.setup
Source: setup.py:162 
First occurred: 04:00:51 (1 occurrences) 
Last logged: 04:00:51

Setup failed for custom integration komfovent_c5: Unable to import component: No module named 'pymodbus.client.asynchronous'`

**Comment by siku2** [comment]
> Newest Version this error, what ca i do?
> 
> `Logger: homeassistant.setup
> Source: setup.py:162 
> First occurred: 04:00:51 (1 occurrences) 
> Last logged: 04:00:51
> 
> Setup failed for custom integration komfovent_c5: Unable to import component: No module named 'pymodbus.client.asynchronous'`

Isn't that just https://github.com/siku2/hass-komfovent-c5/issues/3#issuecomment-1096011150 all over again?

**Comment by colseven** [comment]
Have now hass-komfovent-c5 completely removed from HACS and then added again, now the configuration flow can no longer be loaded. I've tried it several times now... it doesn't work
![bild 2022-07-31 um 10 22 23](https://user-images.githubusercontent.com/63189272/182017357-75e4b93a-bcc4-4892-bbe0-805b6e2a5a2b.jpg)
.
