### ISSUE TITLE
Can’t add to home assistant 

### ISSUE THREAD

**Issue by makaroff112** [siku2/hass-komfovent-c5#59]
Can you please help! I can’t figure out how to make it work with ha: 

Really don’t know what to do…

![image](https://github.com/user-attachments/assets/8aaae370-8cc1-41df-afb9-9aa024e9ffe2)

![IMG_4954](https://github.com/user-attachments/assets/c193689d-d2f4-4335-9da5-52e94d805a84)
![IMG_4957](https://github.com/user-attachments/assets/4b411c68-e48d-4959-96f6-9637fd272e4d)
![IMG_4956](https://github.com/user-attachments/assets/298b87b2-8bcc-4163-87c4-6654b3b27eff)
![IMG_4953](https://github.com/user-attachments/assets/ae2191d0-7dbf-44f6-b580-a83da32ff6eb)

This error originated from a custom integration.

Logger: custom_components.komfovent_c5
Source: helpers/update_coordinator.py:379
integration: Komfovent C5 (documentation, issues)
First occurred: 7:00:12 PM (142 occurrences)
Last logged: 8:26:47 PM

Unexpected error fetching komfovent_c5 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/__init__.py", line 91, in _async_update_data
    return await KomfoventState.read_all(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.client, self.settings_state, is_extended=self.__is_extended
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/komfovent_c5/__init__.py", line 48, in read_all
    monitoring=await api.Monitoring(client).read_all(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        units=settings.flow_units, is_extended=is_extended
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/config/custom_components/komfovent_c5/api/monitoring.py", line 335, in read_all
    block1 = await self.read_block1(units=units, is_extended=is_extended)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/komfovent_c5/api/monitoring.py", line 313, in read_block1
    registers = await self._client.read_many_u16(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/config/custom_components/komfovent_c5/api/client.py", line 114, in read_many_u16
    await self._read_batch(batch_start, count=batch_end - batch_start)
  File "/config/custom_components/komfovent_c5/api/client.py", line 104, in _read_batch
    assert not response.isError()
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by siku2** [comment]
Could you show me the firmware version you're running? You can find it under Alarms/Status -> Controller Status

![image](https://github.com/user-attachments/assets/440515af-06dd-4b6c-bf49-0f591fa05fea)


I suspect you're running a different version that doesn't have all of the same registers.

**Comment by makaroff112** [comment]
> Could you show me the firmware version you're running? You can find it under Alarms/Status -> Controller Status
> 
> ![image](https://private-user-images.githubusercontent.com/16530283/398598592-440515af-06dd-4b6c-bf49-0f591fa05fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNTY3ODEsIm5iZiI6MTczNTI1NjQ4MSwicGF0aCI6Ii8xNjUzMDI4My8zOTg1OTg1OTItNDQwNTE1YWYtMDZkZC00YjZjLWJmNDktMGY1OTFmYTA1ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDIzNDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0YWU1YWViNjIzODNlZGJjMGU2YTQ0MDUxYTk4NjQwM2NiN2ZlNmU1ZTk2NjhmNzdhN2UzYWVmOGJiNDM1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sLDmAX4NRKoMuIEKuG7m_JFtnafo-crFeLITzJZRqtk)
> 
> I suspect you're running a different version that doesn't have all of the same registers.

![IMG_5021](https://github.com/user-attachments/assets/6ebc6cd2-b242-4c68-b9d3-8fdb1ce8ef2e)

**Comment by makaroff112** [comment]
> Could you show me the firmware version you're running? You can find it under Alarms/Status -> Controller Status
> 
> ![image](https://private-user-images.githubusercontent.com/16530283/398598592-440515af-06dd-4b6c-bf49-0f591fa05fea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNTY1NDAsIm5iZiI6MTczNTI1NjI0MCwicGF0aCI6Ii8xNjUzMDI4My8zOTg1OTg1OTItNDQwNTE1YWYtMDZkZC00YjZjLWJmNDktMGY1OTFmYTA1ZmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDIzMzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMGZiMjIxZDFmZTdjODc4ZjM1YTJiNDhiMTg0ZDM3ZGFiYTVhMTFlYmZlZGExOTQ2YjhmMWNmZDIwMDJiZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gD__DUMRFILTHWEfJB93Z_W0LNYJYeliMx1GRrPsO-4)
> 
> I suspect you're running a different version that doesn't have all of the same registers.

![IMG_5020](https://github.com/user-attachments/assets/1854175a-9f7e-4f65-9321-33c7dea88441)


![IMG_5019](https://github.com/user-attachments/assets/e5260b6a-695c-4d8a-84f6-ea20ce37e4ad)

dont know, there is no firmware and don’t know where to see

**Comment by siku2** [comment]
> FW version is identified correctly, what is incorrect is assumption that all FW versions starting v2 has extended registers. I can confirm that v2.110 doesn't have them.

That's exactly why this comment is there :P

https://github.com/siku2/hass-komfovent-c5/blob/e55d48309c356e67cc5ca7d8237c619c31f49b7c/custom_components/komfovent_c5/api/__init__.py#L21-L23

@f5AFfMhv, would be nice if you could open a PR updating the version.
